version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels: [dependencies]
    assignees: [alekc]
    reviewers: [alekc]
    commit-message:
      prefix: "Dependencies:"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /
    groups:
      gomod:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels: [dependencies]
    assignees: [alekc]
    reviewers: [alekc]
    commit-message:
      prefix: "Dependencies:"
    schedule:
      interval: daily
