version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels: [ dependencies ]
    assignees: [ dfroberg ]
    reviewers: [ dfroberg ]
    commit-message:
      prefix: "Dependencies:"
    schedule:
      interval: daily
  - package-ecosystem: "gomod"
    directory: "/"
    labels: [ dependencies ]
    assignees: [ dfroberg ]
    reviewers: [ dfroberg ]
    commit-message:
      prefix: "Dependencies:"
    schedule:
      interval: "daily"
